src/Entity/BaseContent.php
<?php
/**
 *
 *
 *
 *
 */

namespace Kazetenn\Core\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Blameable\Traits\BlameableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Kazetenn\Core\Entity\BaseBlockInterface;
use Kazetenn\Core\Entity\BaseContentInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Uid\UuidV4;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\MappedSuperclass]
abstract class BaseContent implements BaseContentInterface
{
    const DEFAULT_TEMPLATE = '@KazetennCore/content/_block_content_display.twig'; // todo: do something about this

    use TimestampableEntity;
    // todo: set the user by email, do we keep it or do we create a real relation
    use BlameableEntity;

    #[ORM\Id]
    #[ORM\Column(type: 'uuid', nullable: false)]
    protected UuidV4 $id;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: false)]
    protected string $title;

    #[ORM\Column(type: Types::STRING, length: 255, unique: true, nullable: false)]
    protected string $slug;

    // OneToMany association does not work with MappedSuperclass. todo: check how to handle this, can it be handled in a service or not ?
    //    #[ORM\OneToMany(mappedBy: 'campaign', targetEntity: BaseBlock::class)]
    //    #[ORM\OrderBy(["blocOrder" => "asc"])]
    protected Collection $blocks;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: false)]
    protected string $template;

    public function __construct(?string $template = null)
    {
//        $this->blocks = new ArrayCollection();

        $this->id = Uuid::v4();

        if (null === $template) {
            $this->template = self::DEFAULT_TEMPLATE;
        } else {
            $this->template = $template;
        }
    }

    public function getId(): UuidV4
    {
        return $this->id;
    }

    public function setId(UuidV4 $id): void
    {
        $this->id = $id;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function setTitle(string $title): void
    {
        $this->title = $title;
    }

    public function getSlug(): string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): void
    {
        $this->slug = $slug;
    }

    public function getTemplate(): string
    {
        return $this->template;
    }

    public function setTemplate(string $template): void
    {
        $this->template = $template;
    }

    /**
     * @return Collection
     */
    public function getBlocks(): Collection
    {
        return $this->blocks;
    }

    /**
     * This return an ordered array of the direct descendant blocks.
     * @return array<BaseBlockInterface>
     */
    public function getBlocksOrdered(): array{
        $data = $this->blocks;

        $return = [];
        foreach ($data as $datum) {
            if ($datum->getparent() === null) {
                $return[$datum->getBlocOrder()] = $datum;
            }
        }

        return $return;
    }

    /**
     * @param Collection $blocks
     */
    public function setBlocks(Collection $blocks): void
    {
        $this->blocks = $blocks;
    }
}

templates/content_handling/content_index.html.twig
{% for content_name, content_list in contents %}
    <h2 class="subtitle">{{ content_name }}</h2>
    {% for content in content_list %}
        <div style="width: 75%">
            <h3>{{ content_name }} {{ content.id }} - {{ content.Title }} ({{ content.Slug }})</h3>
            <div>
{#                <a href="{{ path('kazetenn_admin_page_show', {'id': content.id}) }}">preview</a>#}
                <a href="{{ path('kazetenn_admin_content_handling', {'content': content.id} ) }}">edit</a>

                {% if content_name == 'page' and null != content.parent %}
                    <a href="{{ path('kazetenn_front_index', {'page_path_1': content.parent.slug, 'page_path_2': content.slug}) }}" target="_blank">Consulter</a>
                {% else %}
                    <a href="{{ path('kazetenn_front_index', {'page_path_1': content.slug}) }}" target="_blank">Consulter</a>
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% else %}
    <div>
        <h2>no records found</h2>
    </div>
{% endfor %}

<a href="{{ path('kazetenn_admin_content_handling') }}">Create new</a>

templates/content_handling/page_form.html.twig
{% extends '@KazetennAdmin/admin_base.html.twig' %}
{% trans_default_domain 'kazetenn_admin' %}

{% block title %}New content{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('admin_page_form') }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('admin_page_form') }}
{% endblock %}

{% block body %}
    {{ form_start(form) }}

    <h3 class="subtitle">{{ 'kazetenn_admin.content_form.title'|trans }}</h3>
    <div class="columns">
        <div class="column">{{ form_row(form.title) }}</div>
        <div class="column">{{ form_row(form.slug) }}</div>

        {% block content_custom_form %}
        {% endblock %}
    </div>

    {% if form.content_type is defined %}
        <div class="columns">
            <div class="column">{{ form_row(form.content_type) }}</div>
        </div>
    {% endif %}

    {% if form.blocks is defined %}
        {% set content_id = form.vars.data.id %}

        <h3 class="subtitle">{{ 'kazetenn_admin.block_form.title'|trans }}</h3>
        <div>
            {% set rendered_blocks = [] %}
            {% set page_order = 0 %}
            {% for block_form in form.blocks.children %}
                {% set block_id = block_form.vars.data.id %}
                {% if block_id not in rendered_blocks and block_form.vars.data.parent is null %}
                    <div class="columns">
                        <div class="column is-10">
                            <div id="{{ block_form.content.vars.id ~ '_header' }}" class="block_text_area_toolbar"></div>
                            {{ form_row(block_form.content) }}
                        </div>
                        <div class="column is-2">
                            {{ form_row(block_form.blocOrder) }}
                            {{ form_row(block_form.align) }}
                        </div>
                    </div>

                    {% set rendered_blocks = rendered_blocks|merge([block_id]) %}

                    <div style="display:flex; flex-direction: {% if block_form.vars.data.align == constant('Kazetenn\\Core\\Entity\\BaseBlock::HORIZONTAL_ALIGN') %}row{% else %}column{% endif %}; justify-content: space-evenly">
                        {% set max_order = 0 %}
                        {% if block_form.vars.data.children|length >= 1 %}
                            {% for child in block_form.vars.data.children %}

                                {% for key, children_block_form in form.blocks.children %}
                                    {% if children_block_form.vars.data.id not in rendered_blocks and children_block_form.vars.data.id == child.id %}
                                        <div class="columns">
                                            <div class="column is-8">
                                                {{ form_row(children_block_form.content) }}
                                            </div>
                                            <div class="column is-3">
                                                {{ form_row(children_block_form.blocOrder) }}
                                                {{ form_row(children_block_form.align) }}
                                            </div>
                                        </div>
                                        {% set rendered_blocks = rendered_blocks|merge([children_block_form.vars.data.id]) %}

                                        {% if children_block_form.vars.data.blocOrder >= max_order %}
                                            {% set max_order = children_block_form.vars.data.blocOrder %}
                                        {% endif %}

                                        {# todo this need a recursion #}
                                    {% endif %}
                                {% endfor %}
                            {% endfor %}
                        {% endif %}

                        <a href="{{ path('kazetenn_admin_content_add_block', {'content': content_id, 'baseBlock': block_id, 'higherOrder': max_order}) }}" type="button">{{ 'kazetenn_admin.add_content.label'|trans }}</a>
                    </div>

                {% endif %}

                {% if block_form.vars.data.blocOrder >= page_order %}
                    {% set page_order = block_form.vars.data.blocOrder %}
                {% endif %}
            {% endfor %}
            <a href="{{ path('kazetenn_admin_content_add_block', {'content': content_id, 'baseBlock': null, 'higherOrder': page_order}) }}" type="button">{{ 'kazetenn_admin.add_content.label'|trans }}</a>
        </div>
        {% do form.blocks.setRendered %}
    {% endif %}
    <div>
        <button type="submit" class="button">{{ 'kazetenn_admin.content_form.button_label'|trans }}</button>
    </div>

    {{ form_end(form) }}
{% endblock %}

templates/content_handling/preview.html.twig
{% extends '@KazetennAdmin/admin_base.html.twig' %}
{% trans_default_domain 'kazetenn_admin' %}

{% block title %}
    {% trans %}kazetenn_admin.page_preview.title{% endtrans %}
{% endblock %}

{% block body %}
    <div id="page_container" class="page_container">
        {% block page_title %}
            <div class="bloc_content">
                <h1 id="page_title" class="page_title">{{ page.title }}</h1>
            </div>
        {% endblock %}

        {# launch de blocks display  #}
        {% for order, data in page.blocksOrdered %}
            {{ include('@KazetennCore/content/_display_block.html.twig', {block: data}) }}
        {% endfor %}
    </div>
{% endblock %}